version: "3"
services:
  app:
    build: ./
    container_name: JanTournamentApp
    env_file: config/enviroment.env
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
